<a href="https://colab.research.google.com/github/akanksha1723/AI_Projects/blob/main/Module_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
2+4

6

**Python for AI**

In [ ]:
print('Hello AI')

Hello AI

In [ ]:
'Hello AI'

'Hello AI'

In [ ]:
name = "Akanksha"
print("hello",name)

hello Akanksha

In [ ]:
name = input("Enter your name")
print("Good Morning", name)

Enter your nameKD
Good Morning KD

In [ ]:
age = int(input("Enter your age"))
print(age)

Enter your age21
21

In [ ]:
age = int(input("Enter your age:"))
print("Age:",age-5)

Enter your age:21
Age: 16

## **Dataset uploading**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/AI_Survey_VAC.xlsx")

In [ ]:
df

,Timestamp,Name,Age,Daily Mobile Usage,Study Hours
0,2026-06-17 21:00:33.625,Dr. Divya Mishra,29,4,4
1,2026-06-18 12:18:01.826,Vansh Tomer,20,8,1
2,2026-06-18 12:18:04.614,Lavish chauhan,23,1,3
3,2026-06-18 12:18:04.829,Utkarsh Chaubey,22,5,6
4,2026-06-18 12:18:07.873,Harshit Upadhyay,21,2,4
...,...,...,...,...,...
138,2026-06-18 12:21:37.766,Tushar kumar,22,3,1
139,2026-06-18 12:21:50.169,Govind Kumar Jha,20,2,4
140,2026-06-18 12:21:57.362,manu,23,8,1
141,2026-06-18 12:21:58.449,Shambhavi,22,1,4
142,2026-06-18 12:22:21.994,Vikas kumar,22,2,4

# **Check & Count the missing value in each column**

In [ ]:
print(df.isnull().sum());

Timestamp              0
Name                   0
Age                    0
Daily Mobile Usage     0
Study Hours            0
dtype: int64

In [ ]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Timestamp, Name , Age , Daily Mobile Usage , Study Hours ]
Index: []

In [ ]:
df.head(5)

,Timestamp,Name,Age,Daily Mobile Usage,Study Hours
0,2026-06-17 21:00:33.625,Dr. Divya Mishra,29,4,4
1,2026-06-18 12:18:01.826,Vansh Tomer,20,8,1
2,2026-06-18 12:18:04.614,Lavish chauhan,23,1,3
3,2026-06-18 12:18:04.829,Utkarsh Chaubey,22,5,6
4,2026-06-18 12:18:07.873,Harshit Upadhyay,21,2,4

In [ ]:
df.tail(6)

,Timestamp,Name,Age,Daily Mobile Usage,Study Hours
137,2026-06-18 12:21:34.437,paridhi chaudhary,23,5,5
138,2026-06-18 12:21:37.766,Tushar kumar,22,3,1
139,2026-06-18 12:21:50.169,Govind Kumar Jha,20,2,4
140,2026-06-18 12:21:57.362,manu,23,8,1
141,2026-06-18 12:21:58.449,Shambhavi,22,1,4
142,2026-06-18 12:22:21.994,Vikas kumar,22,2,4

In [ ]:
df.shape

(143, 5)

In [ ]:
df.columns

Index(['Timestamp', 'Name ', 'Age ', 'Daily Mobile Usage ', 'Study Hours '], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Timestamp            143 non-null    datetime64[ns]
 1   Name                 143 non-null    object
 2   Age                  143 non-null    int64
 3   Daily Mobile Usage   143 non-null    int64
 4   Study Hours          143 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 5.7+ KB

In [ ]:
df.describe()

,Timestamp,Age,Daily Mobile Usage,Study Hours
count,143,143.000000,143.000000,143.000000
mean,2026-06-18 12:12:46.300832,22.216783,4.377622,4.279720
min,2026-06-17 21:00:33.625000,19.000000,1.000000,1.000000
25%,2026-06-18 12:18:37.920000,21.000000,3.000000,3.000000
50%,2026-06-18 12:18:57.870000128,22.000000,4.000000,4.000000
75%,2026-06-18 12:19:31.198499840,23.000000,6.000000,5.000000
max,2026-06-18 12:22:21.994000,29.000000,8.000000,12.000000
std,NaN,1.678949,2.318949,2.715126